include ../../config.mk

.PHONY: clean all reactiontest boopsitest

all: reactiontest boopsitest

reactiontest:
	cd reactiontest ; make all

boopsitest:
	cd boopsitest ; make all

clean:
	cd reactiontest ; make clean
	cd boopsitest ; make clean
